# Ch2.0 NumPy Basics

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.17.4'

In [3]:
pd.__version__

'0.25.3'

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [4]:
list1=[0,1,2,3]

In [5]:
list1

[0, 1, 2, 3]

In [6]:
ar1 = np.array([0, 1, 2, 3]) # 1 dimensional array

In [7]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [8]:
ar1

array([0, 1, 2, 3])

In [9]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [10]:
ar1.shape #shape is a property

(4,)

In [11]:
#ar2.shape, row-major
ar2.shape

(2, 3)

In [12]:
ar3=np.array([[0, 1, 2, 3]]) # 2D-array

In [13]:
ar3

array([[0, 1, 2, 3]])

In [14]:
ar3.shape

(1, 4)

In [15]:
#ar2.size, like len()
ar2.size

6

In [16]:
#ar2.ndim
ar2.ndim

2

In [17]:
ar3.ndim

2

In [18]:
ar2.dtype

dtype('int32')

In [19]:
#ar2 每個元素大小
ar2.itemsize

4

In [20]:
#ar2 總容量(nbytes)
ar2.itemsize * ar2.size

24

In [21]:
ar2.nbytes

24

In [22]:
%timeit ar1 = np.array([0, 1, 2, 3])

728 ns ± 8.74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
%timeit ar1 = np.array((0, 1, 2, 3))

688 ns ± 3.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [24]:
#ar4=np.arange(12); ar4
#一行多個statement 分號隔開
ar4=np.arange(12)
ar4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
# start, end (exclusive)
#ar5=np.arange(3,10,3); ar5
ar5=np.arange(3,10,3)
ar5

array([3, 6, 9])

## NumPy array creation via numpy.linspace
ndarray.linspace generates linear evenly spaced elements between the start and the end

In [26]:
# args - start element,end element, number of elements
#ar6=np.linspace(0,2.0/3,4); ar6
ar6=np.linspace(0,2.0/3,4)
ar6

array([0.        , 0.22222222, 0.44444444, 0.66666667])

In [27]:
type(ar6)

numpy.ndarray

In [28]:
ar6.dtype

dtype('float64')

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

### numpy.ones

In [29]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.zeros

In [30]:
# Produce 4x2 array of zeros.
ar8=np.zeros((4,2)); ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.eye

In [31]:
# Produces identity matrix
ar9 = np.eye(3); ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.diag

In [32]:
# Create diagonal array
ar10=np.diag((2,1,4,6)); ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [33]:
# Using the rand, randn functions
# rand(m) produces uniformly distributed random numbers with range 0 to m
np.random.seed(200) # Set seed
ar11=np.random.rand(3); ar11

array([0.94763226, 0.22654742, 0.59442014])

In [34]:
# randn(m) produces m normally distributed (Gaussian) random numbers
ar12=np.random.randn(5); ar12

array([ 1.4983231 , -0.40666493, -0.09376948,  0.87472083,  0.83141749])

### numpy.empty

In [35]:
ar13=np.empty((3,2)); ar13

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
# compare np.zero & np.empty timeit
%timeit ar13=np.zeros((10,10))
%timeit ar13=np.empty((10,10))

223 ns ± 3.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
222 ns ± 0.903 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### numpy.tile

In [37]:
ar14=np.tile(ar1,2); ar14

array([0, 1, 2, 3, 0, 1, 2, 3])

In [38]:
ar15=np.tile(ar1,(2,3)); ar15

array([[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]])

## NumPy datatypes
Specify the type of contents of a numeric array by using the dtype parameter

In [39]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype='float');
ar

array([ 2., -1.,  6.,  3.])

In [40]:
ar.dtype

dtype('float64')

In [41]:
ar=np.array([2,4,6,8]); ar.dtype

dtype('int32')

In [42]:
#資料型態一致，皆為float
ar=np.array([2.,4,6,8]); ar.dtype

dtype('float64')

In [43]:
#<U9 字串長度固定
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); sar.dtype

dtype('<U9')

In [44]:
sar[0]='changestirngs'

In [45]:
sar

array(['changesti', 'Welcome', 'Tata', 'Goodnight'], dtype='<U9')

In [46]:
bar=np.array([True, False, True]); bar.dtype

dtype('bool')

In [47]:
f_ar = np.array([3,-2,8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [48]:
#取整數部分(保留原有array)
f_ar.astype(int)

array([ 3, -2,  8])

In [49]:
f_ar

array([ 3.  , -2.  ,  8.18])

In [50]:
# copy or view
list1=[1,2,3]
list2=list1
list3=list1.copy()
list4=list1[:]

In [51]:
# view
id(list1),id(list2)

(1771422734088, 1771422734088)

In [52]:
# copy
id(list1),id(list3),id(list4)

(1771422734088, 1771422821384, 1771422821064)

In [53]:
%timeit list3
%timeit list4

19.3 ns ± 4.58 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)
14.1 ns ± 0.144 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


## NumPy indexing and slicing

In [54]:
# print entire array, element 0, element 1, last element.
ar = np.arange(5); print(ar); ar[0], ar[1], ar[-1]

[0 1 2 3 4]


(0, 1, 4)

In [55]:
# 2nd, last and 1st elements
ar=np.arange(5); ar[1], ar[-1], ar[0]

(1, 4, 0)

In [56]:
# Reverse array using ::-1 idiom
ar=np.arange(5); ar[::-1]

array([4, 3, 2, 1, 0])

In [57]:
# like pandas dataframe
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [58]:
ar[1,1]

8

In [59]:
ar[1,1]=5; ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 13]])

In [60]:
# Retrieve row 2
ar[2]

array([11, 12, 13])

In [61]:
ar[2,:]

array([11, 12, 13])

In [62]:
# Retrieve column 1
ar[:,1]

array([ 3,  5, 12])

In [63]:
ar[1][1]

5

In [64]:
%timeit ar[1,1] #快一倍
%timeit ar[1][1] 

105 ns ± 2.67 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
210 ns ± 4.72 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Fancy Indexing

In [65]:
rand = np.random.RandomState(40)
x = rand.randint(100, size=10)
x

array([70, 91,  7, 37, 56, 50, 65, 12, 71, 19])

In [66]:
# access three different elements
[x[3], x[7], x[2]]

[37, 12, 7]

In [67]:
# pass a single list or array of indices to obtain the same result
ind = [3, 7, 2]
x[ind]

array([37, 12,  7])

In [68]:
x[[3,7,2]]

array([37, 12,  7])

##  Array slicing
Arrays can be sliced using the following syntax:<br>
ar[startIndex: endIndex: stepValue].

In [69]:
ar=2*np.arange(6); ar

array([ 0,  2,  4,  6,  8, 10])

In [70]:
ar[1:5:2]

array([2, 6])

In [71]:
# if we wish to include the endIndex value, we need to go above it
ar[1::2] 

array([ 2,  6, 10])

In [72]:
ar[:4]

array([0, 2, 4, 6])

In [73]:
ar[4:]

array([ 8, 10])

In [74]:
# Slice array with stepValue=3
ar[::3]

array([0, 6])

Assignment and slicing can be combined as shown in the following code snippet:

In [75]:
ar

array([ 0,  2,  4,  6,  8, 10])

In [76]:
ar[:3]=1; ar

array([ 1,  1,  1,  6,  8, 10])

In [77]:
# ones輸入為float，只是因為要符合資料型態一致
ar[2:]=np.ones(4);ar

array([1, 1, 1, 1, 1, 1])

In [78]:
np.ones(4).dtype

dtype('float64')

In [79]:
#could not broadcast input array from shape (5) into shape (4)
ar[:4]=np.zeros(5)

ValueError: could not broadcast input array from shape (5) into shape (4)

In [80]:
#could not broadcast input array from shape (2) into shape (4)
ar[:4]=np.zeros(2)

ValueError: could not broadcast input array from shape (2) into shape (4)

## Illustrate the scope of indexing in NumPy
![](figures/2.2-numpy_indexing.png)

In [ ]:
#%%timeit
a=np.zeros((6,6),dtype=np.int32)
ar=np.arange(6)
for i in range(6):
    a[i]=ar+i*10

In [ ]:
a

In [ ]:
a[4:,4:]

In [ ]:
# catch array([13, 33])
a[1:5:2,3]

In [ ]:
# fancy index
a[[1,3],3]

In [81]:
%timeit a[1:5:2,3]
%timeit a[[1,3],3]

NameError: name 'a' is not defined

## Array masking

In [ ]:
np.random.seed(10)
ar=np.random.randint(0,25,10); ar

In [ ]:
evenMask=(ar%2 == 0); evenMask

In [ ]:
evenNums=ar[evenMask]; evenNums

To eliminate missing values

In [ ]:
ar=np.array(['Hungary','Nigeria',
'Guatemala','','Poland','','Japan']); ar

In [ ]:
ar[ar=='']='USA'; ar

In [ ]:
# 置換偶數為 0
np.random.seed(10)
ar=np.random.randint(0,25,10)
ar[ar%2==0]=0;ar

In [ ]:
# 置換偶數平方
np.random.seed(10)
ar=np.random.randint(0,25,10)
ar[ar%2 == 0] ** =2;ar

In [ ]:
np.random.seed(200)
ar=np.random.randint(0,100,10);ar

In [ ]:
ar[ar>=50]=255
ar[ar<50]=0
ar

Arrays of integers can be used to index an array to produce another array

In [ ]:
ar=11*np.arange(0,10); ar

In [ ]:
#fancy index
ar[[1,3,4,2,7]]

In [ ]:
ar[1,3,4,2,7]

Assignment is also possible with array indexing

In [ ]:
ar[[1,3]]=50; ar

## Copies and views

<b>Modifying view modifies original array</b>

In [82]:
ar1=np.arange(12); ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
ar2=ar1[::2]; ar2

array([ 0,  2,  4,  6,  8, 10])

In [84]:
ar2[1]=-1; ar1

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
ar1[2]

-1

In [86]:
ar2[1] is ar1[2]

False

In [87]:
id(ar2[1])==id(ar1[2])

True

In [88]:
np.may_share_memory(ar2[1],ar1[2])

False

In [89]:
np.may_share_memory(ar2,ar1)

True

<b>Use np.copy to force a copy</b><br>

In [90]:
ar=np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [91]:
arc=ar[:3].copy(); arc

array([0, 1, 2])

In [92]:
arc[0]=-1; arc

array([-1,  1,  2])

In [93]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [94]:
ar[0] is arc[0]

False

In [95]:
np.may_share_memory(ar[0],arc[0])

False

In [96]:
np.may_share_memory(ar,arc)

False

In [97]:
np.multiply.outer?