In [ ]:
a=[1,2,3]

In [ ]:
a.index(3)


In [37]:
import numpy as np

In [ ]:
a=[1,2,3]

In [ ]:
a.__add__?

In [ ]:
%run myscript.py


In [ ]:
%?

In [ ]:
help(len)

In [ ]:
%?

In [ ]:
len?

In [ ]:
%run?

In [ ]:
import myscript

In [ ]:
myscript.square(5)

In [ ]:
__name__?


In [1]:
import numpy as np

In [13]:
np.random?

In [4]:
np.random.choice(5)

3

In [48]:
np.random.choice(5,10)

array([3, 0, 1, 1, 4, 4, 2, 4, 1, 1])

In [75]:
a = np.arange(10).reshape(2,5);a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
   template = ([1,2,3], [4,5,6]) 

In [92]:
a=np.empty_like(template);a

array([[-706061376,        399,          0],
       [         0,     131074,          0]])

In [74]:
a=np.empty((2,5));a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.11256817e-306],
       [1.06811422e-306, 1.33510679e-306, 2.22522597e-306,
        1.11261909e-306, 1.78019625e-306]])

In [58]:
a=np.zeros((4,5));a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.empty(a)

TypeError: 'list' object cannot be interpreted as an integer

In [40]:
np.random.RandomState(1).randint(10,size=(2,3))

array([[5, 8, 9],
       [5, 0, 0]])

In [93]:
np.random.multivariate_normal?

In [97]:
np.random.choice?

In [101]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 0)

array([1, 2, 3, 7, 6, 5, 4])

In [102]:
np.partition?

In [103]:
X = rand.rand(10, 2);X

NameError: name 'rand' is not defined